apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: military-ai-stream
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/giuliovigano98/military-ai-streamV7.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-stream-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
