apiVersion: apps/v1
kind: Deployment
metadata:
  name: military-ai-stream
  labels: { app: military-ai-stream }
spec:
  replicas: 1
  selector:
    matchLabels: { app: military-ai-stream }
  template:
    metadata:
      labels: { app: military-ai-stream }
    spec:
      containers:
        - name: app
          image: ghcr.io/giuliovigano98/military-ai-streamv7:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - { name: STREAMLIT_SERVER_HEADLESS, value: "true" }
            - { name: STREAMLIT_SERVER_ADDRESS, value: "0.0.0.0" }
            - { name: STREAMLIT_SERVER_PORT, value: "8501" }
          readinessProbe:
            httpGet: { path: /_stcore/health, port: 8501 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /_stcore/health, port: 8501 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits: { cpu: "1000m", memory: "1Gi" }
