apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/giuliovigano98/military-ai-streamv7
    newName: ghcr.io/giuliovigano98/military-ai-streamv7
    newTag: latest
