name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: giuliovigano98/military-ai-streamv7

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug secrets presence (masked)
        run: |
          echo "MOBILENET len: ${#MODEL_URL_MOBILENET:-0}"
          echo "TANK      len: ${#MODEL_URL_TANK:-0}"
          echo "IFV       len: ${#MODEL_URL_IFV:-0}"
        env:
          MODEL_URL_MOBILENET: ${{ secrets.MODEL_URL_MOBILENET }}
          MODEL_URL_TANK:      ${{ secrets.MODEL_URL_TANK }}
          MODEL_URL_IFV:       ${{ secrets.MODEL_URL_IFV }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha || github.run_id }}
          build-args: |
            MOBILENET_URL=${{ secrets.MODEL_URL_MOBILENET }}
            TANK_URL=${{ secrets.MODEL_URL_TANK }}
            IFV_URL=${{ secrets.MODEL_URL_IFV }}

      - name: Update kustomize image tag
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          sed -i 's|newTag: .*|newTag: '"$SHORT_SHA"'|' k8s/overlays/prod/kustomization.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add k8s/overlays/prod/kustomization.yaml
          git commit -m "chore(ci): bump image tag to ${SHORT_SHA}" || echo "no changes"
          git push
